'*.{xts, js, tsx, jsx}':
  - 'eslint --cache --cache-location ./node_modules/.cache/eslint-cache -fix'
  - 'prettier --loglevel warn --write --cache'
'*.{json, yml}': 'prettier --loglevel warn --write --cache'
'*.{scss}':
  - 'stylelint --cache --cache-location ./node_modules/.cache/stylelint-cache --fix'
  - 'prettier --loglevel warn --write --cache'
